#!/bin/bash

NORMAL=$(tput sgr0)
GREEN=$(tput setaf 2; tput bold)
YELLOW=$(tput setaf 3)
RED=$(tput setaf 1)

function indent {
  echo "$*" | sed -e 's/^/|| /'
}
  
function red() {
    echo -e "$RED$*$NORMAL"
}
      
function green() {
    echo -e "$GREEN$*$NORMAL"
}
          
function yellow() {
    echo -e "$YELLOW$*$NORMAL"
}
              
failed=""
passed=""
              
# recursivly run the arguments in all local directories
for file in $(find -maxdepth 1 -mindepth 1 -type d); do
  green $(basename $file)
  output="$(cd "$file" && $*)"
  if [[ $? -ne 0 ]]; then
    failed="$failed $(basename $file)"
  else
    passed="$passed $(basename $file)"
  fi
  indent "$output"
done
                                 
num_failed=$(echo $failed | wc -w)
                                  
echo
red $num_failed FAILED
echo $failed
                                
exit $num_failed
